"""MCP additions to the existing isolated Edge harness."""

from pathlib import Path


def run(cdp, directory, *, check, close_settings, layout_check, focus_trap_check, send):
    cdp.eval(Path(__file__).with_name("mcp_ui_fixtures.js").read_text(encoding="utf-8"))
    cdp.viewport(1440, 900)
    cdp.click("设置")
    check(cdp.click("MCP"), "MCP 设置分类可导航")
    check(cdp.wait("!!document.querySelector('[aria-label=\"MCP 服务设置\"] input')"), "MCP 状态已读取")
    cdp.click("添加 Exa 搜索示例")
    check(cdp.wait("document.activeElement?.value==='Exa 联网'"), "新增服务聚焦名称")
    check(cdp.eval("window.__fixture.mcp.servers.length===0"), "示例只填草稿，不启动服务")
    cdp.click("保存 MCP 服务")
    check(cdp.wait("window.__fixture.mcp.servers.length===1&&!document.querySelector('[aria-label=\"编辑 MCP 服务\"]')"), "保存 MCP 示例")
    check(cdp.eval("!window.__fixture.mcp.enabled&&!window.__fixture.mcp.servers[0].enabled"), "新增服务保持关闭")
    cdp.click("测试连接／刷新工具")
    check(cdp.wait("document.querySelectorAll('.mcp-tool').length===2"), "连接发现两个已选工具")
    cdp.eval("[...document.querySelectorAll('.mcp-tool label')].find(e=>e.textContent.includes('我信任')).querySelector('input').click()")
    check(cdp.wait("window.__fixture.mcp.servers[0].tools[0].trusted"), "只读授权需要用户明确操作")
    cdp.eval("[...document.querySelectorAll('label')].find(e=>e.textContent.includes('向 Agent 提供')).querySelector('input').click()")
    cdp.wait("window.__fixture.mcp.servers[0].enabled")
    cdp.eval("[...document.querySelectorAll('label')].find(e=>e.textContent.includes('启用 MCP（')).querySelector('input').click()")
    check(cdp.wait("window.__fixture.mcp.enabled"), "MCP 开关即时保存")
    cdp.click("测试连接／刷新工具")
    cdp.wait("document.querySelectorAll('.mcp-tool').length===2")
    focus_trap_check(cdp, "设置")
    cdp.screenshot(directory, "mcp-settings-desktop")
    layout_check(cdp, "MCP 桌面设置", composer=False)
    cdp.viewport(390, 844)
    layout_check(cdp, "MCP 手机设置", composer=False)
    cdp.screenshot(directory, "mcp-settings-mobile")
    close_settings(cdp)
    cdp.viewport(1440, 900)
    cdp.click("查看工具")
    check(cdp.wait("document.body.textContent.includes('MCP · Exa 联网 / web_search_exa')"), "工具清单显示 MCP 来源")
    cdp.click("关闭工具面板")
    for index, mode in enumerate(["自动推理", "先规划", "多专家"]):
        cdp.click(mode)
        cdp.eval("window.__fixture.case='mcp'")
        send(cdp, "使用公开搜索示例")
        card = "document.querySelector('.file-approval[data-approval-id=\"'+window.__fixture.mcpRun.id+'\"]')"
        check(cdp.wait(f"!!({card})"), f"{mode} 显示外部工具审批")
        check(cdp.eval(f"JSON.parse(({card}).querySelector('pre').textContent).query==='公开 MCP 文档'"), "完整调用参数可见")
        if index == 1:
            cdp.viewport(390, 844)
            cdp.eval(f"({card}).scrollIntoView()")
            layout_check(cdp, "MCP 手机确认")
            cdp.screenshot(directory, "mcp-approval-mobile")
            cdp.click("停止生成")
            check(cdp.wait("window.__fixture.mcpCancelled"), "停止确实取消 MCP 流")
            check(cdp.eval(f"!({card}).querySelector('button')"), "停止后不能继续批准")
            cdp.viewport(1440, 900)
        else:
            cdp.click("批准外部调用" if index == 0 else "拒绝外部调用", scope=card)
            check(cdp.wait(f"({card}).dataset.status==={'\"approved\"' if index == 0 else '\"rejected\"'}"), "决定返回后同步审批状态")
            cdp.eval("window.__fixture.mcpRun.finish()")
            check(cdp.wait("!document.querySelector('.composer__stop')"), "MCP 流正常收尾")
            check(cdp.eval("document.body.textContent.includes('会话未保存')"), "独立显示会话保存状态")
    cdp.eval("window.__fixture.case='finished';window.__fixture.restoreMCP()")
